# Generated by Django 4.0.3 on 2022-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('PAS', 'Pasaporte'), ('CE', 'Carnet de Extranjeria')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=50),
        ),
    ]
