# Generated by Django 4.0.3 on 2022-03-08 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_history', '0002_person_document_type_person_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Odontogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_history.customer')),
                ('dental_piece', models.ManyToManyField(to='clinic_history.dentalpiece')),
            ],
        ),
        migrations.AddField(
            model_name='dentalpiece',
            name='treatments',
            field=models.ManyToManyField(to='clinic_history.treatment'),
        ),
    ]
